import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Denver Critical Mass</title>
        <meta
          name="Homepage for information about denver colorado critical mass"
          content="Generated by create next app"
        />
        <link rel="bike icon" href="/favicon.ico" />
      </Head>

      <div className="hero is-fullheight">
        <div className="hero-body">
          <div className="container">
            <Image
              src="/logo.png"
              alt="Denver Critical Mass Logo"
              width="200"
              height="200"
            />
            <h1 className="">
              Last Friday of every month 7PM. Meetup at{" "}
              <a
                href="https://goo.gl/maps/cVHetdaYH31WRxTk7"
                target="_blank"
                rel="noreferrer"
              >
                Thatcher Fountain
              </a>
              .
            </h1>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
